//
// Customer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Customer: Codable {

    public enum Gender: String, Codable { 
        case male = "male"
        case female = "female"
        case other = "other"
    }
    public enum KycStatus: String, Codable { 
        case pending = "pending"
        case inprocess = "inProcess"
        case verified = "verified"
        case failed = "failed"
    }
    /** Unique identifier for the customer */
    public var _id: String?
    /** Customer&#39;s first name. For example, Surya Harsha */
    public var firstName: String?
    /** Customer&#39;s last name. For example, Singh */
    public var lastName: String?
    public var email: String?
    public var mobile: String?
    public var countryCode: String?
    public var age: Int?
    public var gender: Gender?
    public var kycStatus: KycStatus?

    public init(_id: String?, firstName: String?, lastName: String?, email: String?, mobile: String?, countryCode: String?, age: Int?, gender: Gender?, kycStatus: KycStatus?) {
        self._id = _id
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.mobile = mobile
        self.countryCode = countryCode
        self.age = age
        self.gender = gender
        self.kycStatus = kycStatus
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case firstName
        case lastName
        case email
        case mobile
        case countryCode
        case age
        case gender
        case kycStatus
    }


}

