//
// Payment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Payment: Codable {

    public enum Mode: String, Codable { 
        case debit = "debit"
        case credit = "credit"
        case upi = "upi"
        case netbanking = "netbanking"
        case cash = "cash"
    }
    public enum Status: String, Codable { 
        case successful = "successful"
        case failed = "failed"
        case refunded = "refunded"
        case refundinitiated = "refundInitiated"
        case processing = "processing"
    }
    /** Unique identifier for the payment */
    public var _id: String?
    public var plan: Plan?
    /** Instalment serial number for which the payment has been made */
    public var instalmentId: Int?
    /** Mode of payment */
    public var mode: Mode?
    /** Amount paid on the payment */
    public var amount: Int?
    /** Timestamp at which the payment has been made */
    public var createdOn: Date?
    /** Status of the payment */
    public var status: Status?

    public init(_id: String?, plan: Plan?, instalmentId: Int?, mode: Mode?, amount: Int?, createdOn: Date?, status: Status?) {
        self._id = _id
        self.plan = plan
        self.instalmentId = instalmentId
        self.mode = mode
        self.amount = amount
        self.createdOn = createdOn
        self.status = status
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case plan
        case instalmentId
        case mode
        case amount
        case createdOn
        case status
    }


}

