//
// PlanProduct.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Product associated with the plan */

public struct PlanProduct: Codable {




}

