//
// PlanScheme.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Scheme that is used to start a plan */

public struct PlanScheme: Codable {




}

