//
// PlanCustomer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Customer who owns the plan */

public struct PlanCustomer: Codable {




}

