//
// Product.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Product: Codable {

    public enum Status: String, Codable { 
        case active = "active"
        case disabled = "disabled"
        case reviewpending = "reviewPending"
        case reviewrejected = "reviewRejected"
    }
    /** Unique Identifier for the product */
    public var _id: String?
    /** Name of the product */
    public var name: String?
    /** Name of the category that product belongs to */
    public var category: String?
    public var status: Status?
    public var price: Int?
    public var createdOn: Date?
    public var updatedOn: Date?

    public init(_id: String?, name: String?, category: String?, status: Status?, price: Int?, createdOn: Date?, updatedOn: Date?) {
        self._id = _id
        self.name = name
        self.category = category
        self.status = status
        self.price = price
        self.createdOn = createdOn
        self.updatedOn = updatedOn
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case category
        case status
        case price
        case createdOn
        case updatedOn
    }


}

