//
// SchemeRedemptionOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SchemeRedemptionOption: Codable {

    /** month after which the redemption can be applied */
    public var startMonth: Int?
    /** date in the above month after which the redemption can be applied */
    public var startDate: Int?

    public init(startMonth: Int?, startDate: Int?) {
        self.startMonth = startMonth
        self.startDate = startDate
    }


}

