//
// RedemptionAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class RedemptionAPI {
    /**
     Create a new redemption request for a plan
     
     - parameter body: (body) Redemption object that needs to be added 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func addRedemption(body: Redemption, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        addRedemptionWithRequestBuilder(body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Create a new redemption request for a plan
     - POST /redemptions
     - API Key:
       - type: apiKey X-TORTOISE-KEY 
       - name: tortoise_merchant_apiKey
     - API Key:
       - type: apiKey X-TORTOISE-ID 
       - name: tortoise_merchant_appId
     
     - parameter body: (body) Redemption object that needs to be added 

     - returns: RequestBuilder<Void> 
     */
    open class func addRedemptionWithRequestBuilder(body: Redemption) -> RequestBuilder<Void> {
        let path = "/redemptions"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Edit a redemption request for a plan
     
     - parameter redemptionId: (path) ID of the redemption to edit 
     - parameter body: (body) Redemption object that needs to be edited 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func editRedemption(redemptionId: String, body: Redemption, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        editRedemptionWithRequestBuilder(redemptionId: redemptionId, body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Edit a redemption request for a plan
     - PUT /redemptions/{redemptionId}
     - API Key:
       - type: apiKey X-TORTOISE-KEY 
       - name: tortoise_merchant_apiKey
     - API Key:
       - type: apiKey X-TORTOISE-ID 
       - name: tortoise_merchant_appId
     
     - parameter redemptionId: (path) ID of the redemption to edit 
     - parameter body: (body) Redemption object that needs to be edited 

     - returns: RequestBuilder<Void> 
     */
    open class func editRedemptionWithRequestBuilder(redemptionId: String, body: Redemption) -> RequestBuilder<Void> {
        var path = "/redemptions/{redemptionId}"
        let redemptionIdPreEscape = "\(redemptionId)"
        let redemptionIdPostEscape = redemptionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{redemptionId}", with: redemptionIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Fetch all redemption requests
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func fetchAllRedemptions(completion: @escaping ((_ data: [Redemption]?,_ error: Error?) -> Void)) {
        fetchAllRedemptionsWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Fetch all redemption requests
     - GET /redemptions
     - API Key:
       - type: apiKey X-TORTOISE-KEY 
       - name: tortoise_merchant_apiKey
     - API Key:
       - type: apiKey X-TORTOISE-ID 
       - name: tortoise_merchant_appId
     - examples: [{contentType=application/json, example=[ {
  "requestRaisedOn" : "2000-01-23T04:56:07.000+00:00",
  "requestProcessedOn" : "2000-01-23T04:56:07.000+00:00",
  "id" : "id",
  "plan" : {
    "product" : { },
    "planValue" : 0,
    "enrolledOn" : "2000-01-23T04:56:07.000+00:00",
    "totalPaidValue" : 1,
    "scheme" : { },
    "planMaturityDate" : "2000-01-23",
    "nextInstalmentDate" : "2000-01-23",
    "instalmentValue" : 6,
    "completedInstalments" : 5,
    "totalExpectedRedemptionValue" : 5,
    "currentCancellationValue" : 7,
    "lastInstalmentPaidOn" : "2000-01-23T04:56:07.000+00:00",
    "id" : "id",
    "currentRedemptionValue" : 2,
    "customer" : { }
  },
  "status" : "raised"
}, {
  "requestRaisedOn" : "2000-01-23T04:56:07.000+00:00",
  "requestProcessedOn" : "2000-01-23T04:56:07.000+00:00",
  "id" : "id",
  "plan" : {
    "product" : { },
    "planValue" : 0,
    "enrolledOn" : "2000-01-23T04:56:07.000+00:00",
    "totalPaidValue" : 1,
    "scheme" : { },
    "planMaturityDate" : "2000-01-23",
    "nextInstalmentDate" : "2000-01-23",
    "instalmentValue" : 6,
    "completedInstalments" : 5,
    "totalExpectedRedemptionValue" : 5,
    "currentCancellationValue" : 7,
    "lastInstalmentPaidOn" : "2000-01-23T04:56:07.000+00:00",
    "id" : "id",
    "currentRedemptionValue" : 2,
    "customer" : { }
  },
  "status" : "raised"
} ]}]

     - returns: RequestBuilder<[Redemption]> 
     */
    open class func fetchAllRedemptionsWithRequestBuilder() -> RequestBuilder<[Redemption]> {
        let path = "/redemptions"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Redemption]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get a redemption request by ID
     
     - parameter redemptionId: (path) ID of the redemption to fetch 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getRedemption(redemptionId: String, completion: @escaping ((_ data: Redemption?,_ error: Error?) -> Void)) {
        getRedemptionWithRequestBuilder(redemptionId: redemptionId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get a redemption request by ID
     - GET /redemptions/{redemptionId}
     - API Key:
       - type: apiKey X-TORTOISE-KEY 
       - name: tortoise_merchant_apiKey
     - API Key:
       - type: apiKey X-TORTOISE-ID 
       - name: tortoise_merchant_appId
     - examples: [{contentType=application/json, example={
  "requestRaisedOn" : "2000-01-23T04:56:07.000+00:00",
  "requestProcessedOn" : "2000-01-23T04:56:07.000+00:00",
  "id" : "id",
  "plan" : {
    "product" : { },
    "planValue" : 0,
    "enrolledOn" : "2000-01-23T04:56:07.000+00:00",
    "totalPaidValue" : 1,
    "scheme" : { },
    "planMaturityDate" : "2000-01-23",
    "nextInstalmentDate" : "2000-01-23",
    "instalmentValue" : 6,
    "completedInstalments" : 5,
    "totalExpectedRedemptionValue" : 5,
    "currentCancellationValue" : 7,
    "lastInstalmentPaidOn" : "2000-01-23T04:56:07.000+00:00",
    "id" : "id",
    "currentRedemptionValue" : 2,
    "customer" : { }
  },
  "status" : "raised"
}}]
     
     - parameter redemptionId: (path) ID of the redemption to fetch 

     - returns: RequestBuilder<Redemption> 
     */
    open class func getRedemptionWithRequestBuilder(redemptionId: String) -> RequestBuilder<Redemption> {
        var path = "/redemptions/{redemptionId}"
        let redemptionIdPreEscape = "\(redemptionId)"
        let redemptionIdPostEscape = redemptionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{redemptionId}", with: redemptionIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Redemption>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
